import { Hono } from "hono";
import type { ObjectStorage } from "../services/object-storage.js";

/**
 * Exploration routes (audit Phase 3.5). Currently exposes a single
 * endpoint: GET /:explorationId/preview/:candidateId returns a signed
 * URL to the rendered preview video stored under
 * `previews/{explorationId}/{candidateId}.mp4` in R2.
 *
 * Phase 3 status: the URL minting works today. The actual MP4 only
 * exists once HeadlessRenderer is wired (Phase 3.1 + 3.3) — until then
 * a successful 200 with a signed URL is returned, and following the
 * URL yields R2's "object does not exist" error. That's intentional:
 * it lets the web side build against the real URL shape now.
 */
export interface ExplorationRouterDeps {
  objectStorage?: ObjectStorage;
}

export function createExplorationRouter(deps: ExplorationRouterDeps = {}): Hono {
  const { objectStorage } = deps;
  const router = new Hono();

  router.get("/:explorationId/preview/:candidateId", async (c) => {
    if (!objectStorage) {
      return c.json(
        { error: "ObjectStorage not configured", available: false },
        503,
      );
    }
    const explorationId = c.req.param("explorationId");
    const candidateId = c.req.param("candidateId");

    // Storage key shape mirrors what HeadlessRenderer.exportVideo
    // uploads. The candidate's filename is generated by ObjectStorage's
    // upload (random UUID under the prefix) — for now we list the
    // prefix and pick the candidate-tagged file. Real impl will record
    // the storageKey in the explorations table at upload time so this
    // route just looks it up.
    const storageKey = `previews/${explorationId}/${candidateId}.mp4`;

    try {
      const url = await objectStorage.getSignedUrl(storageKey);
      return c.json({ explorationId, candidateId, url });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return c.json({ error: msg }, 404);
    }
  });

  return router;
}
