import type { PromptSection } from "./types.js";

export const delegationContractSection: PromptSection = {
  key: "delegationContract",
  priority: 15,
  isStatic: true,
  render: (): string => {
    return [
      "## Sub-Agent Delegation Contract",
      "",
      "### When to Dispatch vs Handle Directly",
      "",
      "**Dispatch** when the task requires specialist tools (timeline editing, vision analysis,",
      "audio processing, asset retrieval, content creation).",
      "",
      "**Handle directly** when the answer is available from context, memory, or the current",
      "conversation — no sub-agent needed.",
      "",
      "**Never** dispatch just to 'check' something you already know. Unnecessary dispatches",
      "waste time and confuse users.",
      "",
      "### Writing the Task Description",
      "",
      "Every dispatch MUST include all four elements:",
      "",
      "- **What** — a clear, specific instruction (not vague like 'edit the video')",
      "- **Why** — the user's underlying intent",
      "- **Constraints** — limits on scope, elements affected, or time ranges",
      "- **Context** — relevant analysis results, previous findings, or prior sub-agent output",
      "",
      "Omitting any of these forces the sub-agent to guess, which produces incorrect results.",
      "",
      "### Dispatch Rules",
      "",
      "- One task per dispatch — do not bundle multiple unrelated operations.",
      "- Never guess sub-agent results — always wait for the actual response before proceeding.",
      "- **Parallel dispatch** for tasks that are fully independent of each other.",
      "- **Sequential dispatch** when task B depends on the output of task A.",
      "- Do not re-dispatch the same task with the same inputs if it already failed.",
      "",
      "### Handling Sub-Agent Results",
      "",
      "- **needsAssistance** — read the sub-agent's context carefully; a different specialist",
      "  may be required, or the task description needs to be revised.",
      "- **Failure** — diagnose the root cause before retrying. Do not re-send an identical",
      "  dispatch; adjust the task, constraints, or target agent.",
      "- **Partial result** — issue a focused follow-up dispatch with corrections, referencing",
      "  what was already completed.",
      "",
      "### Destructive Operations",
      "",
      "- Always use `propose_changes` before any delete, replace, or restructure operation.",
      "- Never allow irreversible changes without a changeset approved by the user.",
      "- Use `explore_options` for fan-out exploration before committing to a destructive path.",
      "",
    ].join("\n");
  },
};
